import csv
import re
import unicodedata
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

from openpyxl import load_workbook

QR_CSV = Path("supabase/participants_from_pdf.csv")
RESP_XLSX = Path("responses.xlsx")
OUT_CSV = Path("supabase/merged_participants_choices.csv")
OUT_SQL = Path("supabase/import_participants_choices.sql")


def normalize_text(value: str) -> str:
    text = unicodedata.normalize("NFKD", value)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "", text)
    return text


def normalize_society(value: str) -> str:
    text = value.strip().lower()
    text = text.replace("msu- iit", "msu-iit")
    text = text.replace("msu - main", "msu-main")
    text = text.replace("  ", " ")
    return normalize_text(text)


def response_name_to_display(value: str) -> str:
    text = value.strip()
    if "," not in text:
        return " ".join(text.split())

    parts = [p.strip() for p in text.split(",")]
    if len(parts) >= 2:
        last = parts[0]
        rest = " ".join(parts[1:]).strip()
        display = f"{rest} {last}".strip()
        return " ".join(display.split())

    return " ".join(text.split())


def normalize_name(value: str) -> str:
    return normalize_text(" ".join(value.split()))


@dataclass
class QrRow:
    unique_id: str
    full_name: str
    society: str
    qr_raw: str


@dataclass
class ResponseRow:
    full_name: str
    society: str
    food_choice: str
    bundle_choice: str


@dataclass
class MergedRow:
    unique_id: str
    full_name: str
    society: str
    food_choice: str
    bundle_choice: str
    match_method: str


def load_qr_rows() -> list[QrRow]:
    rows: list[QrRow] = []
    with QR_CSV.open(encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            uid = (r.get("unique_id") or "").strip()
            name = (r.get("full_name") or "").strip()
            society = (r.get("society") or "").strip()
            qr_raw = (r.get("qr_raw") or "").strip()
            if uid and name:
                rows.append(QrRow(uid, name, society, qr_raw))
    return rows


def load_response_rows() -> list[ResponseRow]:
    wb = load_workbook(RESP_XLSX, data_only=True)
    ws = wb["Form Responses 1"]
    headers = [ws.cell(1, c).value for c in range(1, ws.max_column + 1)]
    header_map = {str(h).strip(): i for i, h in enumerate(headers)}

    name_col = header_map["Name (Last Name, First Name,  Middle Name)"]
    society_col = header_map["Home Chemistry Society"]
    food_col = header_map["Choose one. (Breakfast Only)"]
    bundle_col = header_map["Choice of Bundle"]

    rows: list[ResponseRow] = []
    for r in range(2, ws.max_row + 1):
        vals = [ws.cell(r, c).value for c in range(1, ws.max_column + 1)]
        if not any(v not in (None, "") for v in vals):
            continue

        raw_name = vals[name_col]
        raw_society = vals[society_col]
        if raw_name in (None, ""):
            continue

        name_display = response_name_to_display(str(raw_name))
        society = "" if raw_society in (None, "") else str(raw_society).strip()
        food = "" if vals[food_col] in (None, "") else str(vals[food_col]).strip()
        bundle = "" if vals[bundle_col] in (None, "") else str(vals[bundle_col]).strip()
        rows.append(ResponseRow(name_display, society, food, bundle))

    return rows


def esc(value: str) -> str:
    return value.replace("'", "''")


def build_sql(rows: list[MergedRow]) -> str:
    lines = ["-- Generated by scripts/merge_qr_and_responses.py", "begin;"]

    for row in rows:
        lines.append(
            "insert into public.participants (unique_id, full_name, society) "
            f"values ('{esc(row.unique_id)}', '{esc(row.full_name)}', '{esc(row.society)}') "
            "on conflict (unique_id) do update set "
            "full_name = excluded.full_name, society = excluded.society;"
        )

    for row in rows:
        if row.food_choice:
            lines.append(
                "insert into public.food_choices (participant_id, choice_date, choice) "
                "select id, current_date, "
                f"'{esc(row.food_choice)}' from public.participants "
                f"where unique_id = '{esc(row.unique_id)}' "
                "on conflict (participant_id, choice_date) do update set choice = excluded.choice;"
            )

    for row in rows:
        if row.bundle_choice:
            lines.append(
                "insert into public.bundle_choices (participant_id, choice_date, choice) "
                "select id, current_date, "
                f"'{esc(row.bundle_choice)}' from public.participants "
                f"where unique_id = '{esc(row.unique_id)}' "
                "on conflict (participant_id, choice_date) do update set choice = excluded.choice;"
            )

    lines.append("commit;")
    return "\n".join(lines) + "\n"


def main() -> None:
    qr_rows = load_qr_rows()
    response_rows = load_response_rows()

    by_name_soc: dict[tuple[str, str], list[ResponseRow]] = defaultdict(list)
    by_name: dict[str, list[ResponseRow]] = defaultdict(list)

    for row in response_rows:
        n = normalize_name(row.full_name)
        s = normalize_society(row.society)
        by_name_soc[(n, s)].append(row)
        by_name[n].append(row)

    merged: list[MergedRow] = []
    match_counter = Counter()

    for qr in qr_rows:
        n = normalize_name(qr.full_name)
        s = normalize_society(qr.society)

        matched: ResponseRow | None = None
        method = "none"

        exact_list = by_name_soc.get((n, s), [])
        if exact_list:
            matched = exact_list[0]
            method = "name+society"
        else:
            name_list = by_name.get(n, [])
            if len(name_list) == 1:
                matched = name_list[0]
                method = "name-only"

        food = matched.food_choice if matched else ""
        bundle = matched.bundle_choice if matched else ""

        merged.append(
            MergedRow(
                unique_id=qr.unique_id,
                full_name=qr.full_name,
                society=qr.society,
                food_choice=food,
                bundle_choice=bundle,
                match_method=method,
            )
        )
        match_counter[method] += 1

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "unique_id",
                "full_name",
                "society",
                "food_choice",
                "bundle_choice",
                "match_method",
            ],
        )
        writer.writeheader()
        for row in merged:
            writer.writerow(
                {
                    "unique_id": row.unique_id,
                    "full_name": row.full_name,
                    "society": row.society,
                    "food_choice": row.food_choice,
                    "bundle_choice": row.bundle_choice,
                    "match_method": row.match_method,
                }
            )

    OUT_SQL.write_text(build_sql(merged), encoding="utf-8")

    print("qr_rows:", len(qr_rows))
    print("response_rows:", len(response_rows))
    print("merged_rows:", len(merged))
    print("matched_name_society:", match_counter["name+society"])
    print("matched_name_only:", match_counter["name-only"])
    print("unmatched:", match_counter["none"])
    print("with_food:", sum(1 for r in merged if r.food_choice))
    print("with_bundle:", sum(1 for r in merged if r.bundle_choice))
    print("wrote_csv:", OUT_CSV)
    print("wrote_sql:", OUT_SQL)


if __name__ == "__main__":
    main()
